### PR TITLE
Added German (de_DE) translation

### PR DESCRIPTION
**Pull request by marrobHD**
Hi,
i added the translation for German (de_DE).

### CODE REVIEW

**Comment by marrobHD** [comment]
Wrong repo.

**Comment by JakeSulyDGL** [comment]
Cool

**Comment by VR-25** [comment]
Please go to the main [repo](https://github.com/vr-25/acc), thanks!

**Comment by VR-25** [comment]
Please go to the main [repo](https://github.com/vr-25/acc), thanks!

**Pull request closed without merging**
